#! /bin/bash

cachedir=cache
gateways=($(netstat -rn | grep '^\(default\|0\.0\.0\.0\)' | awk '{print $2}'))
default_gateway=${gateways[0]}

header() {
    cat <<HEADER
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>

<Style id="source">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/catarinaacsilva/kmltraceroute/master/icons/flag.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="jump">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/catarinaacsilva/kmltraceroute/master/icons/server.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="destination">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/catarinaacsilva/kmltraceroute/master/icons/destination.png</href>
</Icon>
</IconStyle>
</Style>

HEADER
}

gettraceroute4() {
    storename="$cachedir/tcptraceroute-$1"
    tmpname="$storename-$$.new"
    if [ -s "$storename" ] ; then
	cat "$storename"
    else
    traceroute -T -n $1 | tee "$tmpname"
    fi |
	tail -n +2 |
	sed 's/\* //g' |
	awk '{print $2}' |
	grep -E '^([0-9]{1,3}[\.]){3}[0-9]{1,3}$'
    if [ -s "$tmpname" ] ; then
	mv "$tmpname" "$storename"
    fi
}

getIP4location() {
    local C=""
    
    if [ -e GeoIP-override.txt ] ; then
	C="$(grep "^$IP " GeoIP-override.txt | cut -d"#" -f1)"
    fi
   
    if [ -z "$C" ] && [ -e "$cachedir/GeoIP-cache.txt" ] ; then
    C=$(grep -m 1 "^$IP " "$cachedir/GeoIP-cache.txt")
    fi

    if [ "$C" ]; then
	LONG=$(echo "$C" |cut -d" " -f2)
	LAT=$(echo "$C" |cut -d" " -f3)
	return
    fi
    LONG=
    LAT=
    
    if [ "$default_gateway" = "$IP" ]; then
    url=https://freegeoip.live/json/
    else
    url=https://freegeoip.live/json/$IP
    fi
    
    LOCATION=$(curl -s $url | jq -r '.longitude, .latitude')

    if [ "$LOCATION" ]; then
    read LONG LAT < <(echo $LOCATION)
    echo $IP $LONG $LAT >> "$cachedir/GeoIP-cache.txt"
    fi

}

tracehost() {
    targetip="$1"
    targetname="$2"
    local LONGLATS=""
    local ICON=""
    targetreverse=$(getent hosts "$targetip"|awk '{print $2}')
    echo "<!-- traceroute for $targetname / $targetreverse [$targetip] -->"
    IPS=($(gettraceroute4 "$targetip"))
    for IP in "${IPS[@]}"; do
    getIP4location "$IP"
	name=$(getent hosts "$IP" | awk '{print $2}')
	if [ "$LONG" ] ; then
	    LONGLAT="${LONG},${LAT} "
	    LONGLATS="${LONGLATS}${LONGLAT}\n"

        ICON="jump"

        if [ "$IP" = "${IPS[0]}" ]; then
            ICON="source"
        fi

	    if [ "$targetip" = "$IP" ]; then
		labelname="$targetname"
        ICON="destination"
	    else
		labelname=""
	    fi
            cat <<EOF
<Placemark>
  <name>$labelname</name>
  <description>GeoIP position for $name [$IP]</description>
  <styleUrl>#$ICON</styleUrl> 
  <Point><coordinates>$LONGLAT</coordinates></Point>
</Placemark>
EOF
	else
	    echo "<!-- missing GeoIP info for $name [$IP] -->"
	fi
    done;

    echo "<Placemark><name>Path for $targetname / $targetreverse [$targetip]</name><LineString>"
    echo "  <coordinates>"
    #echo -e "${LONGLATS::-2}"
    echo -e "$LONGLATS"
    echo "  </coordinates></LineString></Placemark>"
    echo
}

footer() {
    cat <<FOOTER
  </Document>
</kml>
FOOTER
}

usage() {
    cat <<EOF
Usage: $0 <host> [<host> ...]

Collect TCP traceroutes using 'sudo tcptraceroute' and up each route
using GeoIP and output a KML file to stdout with the georeferenced
traces.

The traceoutes are cached in ./cache/, and the GeoIP location data can
be replaced with entires in GeoIP-override.txt.

EOF
    }

if [ -z "$1" ]; then
    usage
    exit 1
fi

header
for h in "$@" ; do
    for ip in $(host $h|awk '/has address/ {print $4}'); do
	tracehost "$ip" "$h"
    done
done
footer
